version: "3"
services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
  api:
    build:
      dockerfile: Dockerfile.dev
      context: sirin-test-backend
    volumes:
      - /app/node_modules
      - ./sirin-test-backend:/app
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=postgres
      - DB_PASSWORD=admin
      - DB_PORT=5432
      - JWT_SECRET=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYxOTEwMjczMiwiaWF0IjoxNjE5MTAyNzMyfQ.jmc1_olJqGxUHOLdzdo-K5v9BjBumRzEze8PHF3N-Pg
    ports:
      - 5000:5000
    depends_on:
      - db
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile.dev
      context: sirin-test-frontend
    volumes:
      - /app/node_modules
      - ./sirin-test-frontend:/app
    depends_on:
      - api
